# Generated by Django 5.0.3 on 2024-05-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='InstrumentType',
            new_name='instrument_type',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='musicianmodel',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
    ]
