# Generated by Django 5.0.3 on 2024-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_rename_email_musicianmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='instrument_type',
            field=models.TextField(),
        ),
    ]
